// GENERATED by tools/build-sw.mjs — do not edit by hand.
// Keeps every game file on the device so it works without internet.
const VERSION = 'b129c1d899';
const CACHE = 'drnam-chem-games-' + VERSION;
const FILES = [
  "./",
  "./brand/fonts/league-spartan-latin-400-normal.woff2",
  "./brand/fonts/league-spartan-latin-700-normal.woff2",
  "./brand/fonts/league-spartan-latin-800-normal.woff2",
  "./brand/fonts/questrial-latin-400-normal.woff2",
  "./brand/logos/ADD-LOGOS-HERE.txt",
  "./brand/logos/chemistry-with-dr-nam-logo.jpg",
  "./brand/logos/uitm-di-hatiku-motto.png",
  "./brand/logos/uitm-logo-full.png",
  "./css/app.css",
  "./css/lewis.css",
  "./css/tokens.css",
  "./data/lewis/elements.json",
  "./data/lewis/levels.json",
  "./data/lewis/molecules.json",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/icon-maskable-512.png",
  "./index.html",
  "./js/activities/lewis/board.js",
  "./js/activities/lewis/index.js",
  "./js/activities/lewis/rules.js",
  "./js/activities/registry.js",
  "./js/doodles.js",
  "./js/drag.js",
  "./js/gestures/classify.js",
  "./js/gestures/engine.js",
  "./js/i18n.js",
  "./js/main.js",
  "./js/sound.js",
  "./js/store.js",
  "./js/tutorial.js",
  "./js/ui.js",
  "./lang/en.json",
  "./lang/ms.json",
  "./manifest.webmanifest",
  "./vendor/mediapipe-hands/hand_landmark_lite.tflite",
  "./vendor/mediapipe-hands/hands.binarypb",
  "./vendor/mediapipe-hands/hands.js",
  "./vendor/mediapipe-hands/hands_solution_packed_assets.data",
  "./vendor/mediapipe-hands/hands_solution_packed_assets_loader.js",
  "./vendor/mediapipe-hands/hands_solution_simd_wasm_bin.data",
  "./vendor/mediapipe-hands/hands_solution_simd_wasm_bin.js",
  "./vendor/mediapipe-hands/hands_solution_simd_wasm_bin.wasm",
  "./vendor/three/three.core.js",
  "./vendor/three/three.module.js"
];

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    await cache.addAll(FILES);
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) if (key !== CACHE) await caches.delete(key);
    await self.clients.claim();
    for (const c of await self.clients.matchAll()) c.postMessage({ type: 'precached', version: VERSION });
  })());
});

self.addEventListener('fetch', event => {
  const req = event.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  event.respondWith((async () => {
    const cached = await caches.match(req, { ignoreSearch: true });
    if (cached) return cached;
    try {
      const res = await fetch(req);
      if (res.ok) (await caches.open(CACHE)).put(req, res.clone());
      return res;
    } catch (err) {
      if (req.mode === 'navigate') return caches.match('./index.html');
      throw err;
    }
  })());
});
