// Writes sw.js with the full list of game files to keep for offline play.
// Run after adding or changing files:  node tools/build-sw.mjs
import { readdirSync, statSync, readFileSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { createHash } from 'node:crypto';

const root = new URL('..', import.meta.url).pathname;
const include = ['index.html', 'manifest.webmanifest', 'css', 'js', 'lang', 'brand', 'icons', 'vendor', 'data'];
// Skipped: docs, source maps, and the non-SIMD wasm (only very old browsers need it; cached on demand).
const skip = /(^|\/)(\.|LICENSE|README|.*\.md$|.*\.map$|hands_solution_wasm_bin\.)/;

const files = [];
const walk = p => {
  const full = join(root, p);
  if (statSync(full).isDirectory()) readdirSync(full).forEach(f => walk(join(p, f)));
  else if (!skip.test(p)) files.push(p);
};
include.forEach(walk);
files.sort();

const hash = createHash('sha256');
for (const f of files) hash.update(f).update(readFileSync(join(root, f)));
const version = hash.digest('hex').slice(0, 10);

const sw = `// GENERATED by tools/build-sw.mjs — do not edit by hand.
// Keeps every game file on the device so it works without internet.
const VERSION = '${version}';
const CACHE = 'drnam-chem-games-' + VERSION;
const FILES = ${JSON.stringify(['./', ...files.map(f => './' + f)], null, 2)};

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    await cache.addAll(FILES);
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) if (key !== CACHE) await caches.delete(key);
    await self.clients.claim();
    for (const c of await self.clients.matchAll()) c.postMessage({ type: 'precached', version: VERSION });
  })());
});

self.addEventListener('fetch', event => {
  const req = event.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  event.respondWith((async () => {
    const cached = await caches.match(req, { ignoreSearch: true });
    if (cached) return cached;
    try {
      const res = await fetch(req);
      if (res.ok) (await caches.open(CACHE)).put(req, res.clone());
      return res;
    } catch (err) {
      if (req.mode === 'navigate') return caches.match('./index.html');
      throw err;
    }
  })());
});
`;
writeFileSync(join(root, 'sw.js'), sw);
const size = files.reduce((s, f) => s + statSync(join(root, f)).size, 0);
console.log(`sw.js written: ${files.length} files, ${(size / 1048576).toFixed(1)} MB, version ${version}`);
